/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.geekorum.gradle.avdl

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GradleAvdlPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'com.geekorum.gradle.avdl.greeting'")
            }
        }
    }
}
